namespace SpriteKind {
    export const Objects = SpriteKind.create()
    export const StairA_kind = SpriteKind.create()
    export const Stairs = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    Directions = 12
})
scene.onHitWall(SpriteKind.Player, function (sprite, location) {
    if (Hero.tileKindAt(TileDirection.Top, sprites.dungeon.chestClosed)) {
        if (game.ask("Open Box?")) {
            tiles.setTileAt(location, assets.tile`myTile`)
            game.showLongText("You received a Key", DialogLayout.Bottom)
            Key = sprites.create(img`
                ................
                ................
                ...8888.........
                ..8888888888....
                ..88..8...8.8...
                ..88..8...8.8...
                ..88888.....8...
                ...888..........
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                `, SpriteKind.Objects)
            tiles.placeOnTile(Key, location)
            Key.follow(Hero, 500)
        }
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Attack = 1
    pause(500)
    Attack = 0
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    Directions = 9
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    Directions = 3
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    Directions = 6
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairLarge, function (sprite, location) {
    if (Hero.overlapsWith(StairsA)) {
        scene.centerCameraAt(0, 184)
        tiles.placeOnTile(Hero, tiles.getTileLocation(1, 13))
        tiles.placeOnTile(Key, tiles.getTileLocation(1, 13))
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairSouth, function (sprite, location) {
    if (Hero.overlapsWith(StairsB)) {
        scene.centerCameraAt(0, 0)
        tiles.placeOnTile(Hero, tiles.getTileLocation(1, 2))
        tiles.placeOnTile(Key, tiles.getTileLocation(1, 2))
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (Attack == 1) {
        otherSprite.destroy(effects.fire, 200)
    } else {
        info.changeLifeBy(-1)
        if (otherSprite.vx < 0) {
            otherSprite.x += 16
        } else {
            otherSprite.x += -16
        }
    }
})
let Attack = 0
let Key: Sprite = null
let Directions = 0
let StairsB: Sprite = null
let StairsA: Sprite = null
let Hero: Sprite = null
tiles.setTilemap(tilemap`level1`)
info.setLife(3)
Hero = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Hero, 100, 100)
tiles.placeOnTile(Hero, tiles.getTileLocation(4, 4))
StairsA = sprites.create(sprites.dungeon.stairLarge, SpriteKind.Stairs)
tiles.placeOnTile(StairsA, tiles.getTileLocation(1, 1))
StairsB = sprites.create(sprites.dungeon.stairSouth, SpriteKind.Stairs)
tiles.placeOnTile(StairsB, tiles.getTileLocation(1, 14))
let myEnemy = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ....7.fd11111111df......
    ...7..fd11111111df......
    ...7..fd11111111df......
    ...7..fddd1111dddff.....
    ...77.fbdbfddfbdbfcf....
    ...777fcdcf11fcdcfbf....
    ....77fffbdb1bdffcf.....
    ....fcb1bcffffff........
    ....f1c1c1ffffff........
    ....fdfdfdfffff.........
    .....f.f.f..............
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
tiles.placeOnTile(myEnemy, tiles.getTileLocation(1, 10))
myEnemy.follow(Hero, 30)
forever(function () {
    if (Attack == 0) {
        if (Directions == 12) {
            Hero.setImage(img`
                . . . . . f f f f . . . . . . . 
                . . . f f e e e e f f . . . . . 
                . . f e e e f f e e e f . . . . 
                . f f f f f 2 2 f f f f f . . . 
                . f f e 2 e 2 2 e 2 e f f . . . 
                . f e 2 f 2 f f 2 f 2 e f . . . 
                . f f f 2 2 e e 2 2 f f f . . . 
                f f e f 2 f e e f 2 f e f f . . 
                f e e f f e e e e f e e e f . . 
                . f e e e e e e e e e e f . . . 
                . . f e e e e e e e e f . . . . 
                . e 4 f f f f f f f f 4 e . . . 
                . 4 d f 2 2 2 2 2 2 f d 4 . . . 
                . 4 4 f 4 4 4 4 4 4 f 4 4 . . . 
                . . . . f f f f f f . . . . . . 
                . . . . f f . . f f . . . . . . 
                `)
        }
        if (Directions == 3) {
            Hero.setImage(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . f f f f f f . . . . 
                . . . . f f e e e e f 2 f . . . 
                . . . f f e e e e f 2 2 2 f . . 
                . . . f e e e f f e e e e f . . 
                . . . f f f f e e 2 2 2 2 e f . 
                . . . f e 2 2 2 f f f f e 2 f . 
                . . f f f f f f f e e e f f f . 
                . . f f e 4 4 e b f 4 4 e e f . 
                . . f e e 4 d 4 1 f d d e f . . 
                . . . f e e e e e d d d f . . . 
                . . . . . f 4 d d e 4 e f . . . 
                . . . . . f e d d e 2 2 f . . . 
                . . . . f f f e e f 5 5 f f . . 
                . . . . f f f f f f f f f f . . 
                . . . . . f f . . . f f f . . . 
                `)
        }
        if (Directions == 6) {
            Hero.setImage(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . f f f f . . . . . . 
                . . . . f f f 2 2 f f f . . . . 
                . . . f f f 2 2 2 2 f f f . . . 
                . . f f f e e e e e e f f f . . 
                . . f e e 2 2 2 2 2 2 e f f . . 
                . f f e 2 f f f f f f 2 e f f . 
                . f f f f f e e e e f f f f f . 
                . . f e f b f 4 4 f b f e f . . 
                . . f e 4 1 f d d f 1 4 e f . . 
                . . e f e 4 d d d d 4 e f . . . 
                . . e 4 d d e 2 2 2 2 f e f . . 
                . . . e d d e 2 2 2 2 f 4 e . . 
                . . . . e e f 5 5 4 4 f . . . . 
                . . . . . f f f f f f f . . . . 
                . . . . . . . . . f f f . . . . 
                `)
        }
        if (Directions == 9) {
            Hero.setImage(img`
                . . . . . . . . . . . . . . . . 
                . . . . f f f f f f . . . . . . 
                . . . f 2 f e e e e f f . . . . 
                . . f 2 2 2 f e e e e f f . . . 
                . . f e e e e f f e e e f . . . 
                . f e 2 2 2 2 e e f f f f . . . 
                . f 2 e f f f f 2 2 2 e f . . . 
                . f f f e e e f f f f f f f . . 
                . f e e 4 4 f b e 4 4 e f f . . 
                . . f e d d f 1 4 d 4 e e f . . 
                . . . f d d d e e e e e f . . . 
                . . . f e 4 e d d 4 f . . . . . 
                . . . f 2 2 e d d e f . . . . . 
                . . f f 5 5 f e e f f f . . . . 
                . . f f f f f f f f f f . . . . 
                . . . f f f . . . f f . . . . . 
                `)
        }
    } else {
        if (Directions == 12) {
            Hero.setImage(img`
                ........................
                ....ffffff..............
                ..ffeeeef2f.............
                .ffeeeef222f............
                .feeeffeeeef...cc.......
                .ffffee2222ef.cdc.......
                .fe222ffffe2fcddc.......
                fffffffeeeffcddc........
                ffe44ebf44ecddc.........
                fee4d41fddecdc..........
                .feee4dddedccc..........
                ..ffee44e4dde...........
                ...f222244ee............
                ...f2222e2f.............
                ...f444455f.............
                ....ffffff..............
                .....fff................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `)
        }
        if (Directions == 3) {
            Hero.setImage(img`
                .......ff...............
                ....ffff2ff.............
                ..ffeeeef2ff............
                .ffeeeeef22ff...........
                .feeeeffeeeef...........
                .fffffee2222ef..........
                fffe222ffffe2f..........
                ffffffffeeefff..........
                fefe44ebf44eef..........
                .fee4d4bfddef...........
                ..feee4dddee.c..........
                ...f2222eeddeccccccc....
                ...f444e44ddecddddd.....
                ...fffffeeee.ccccc......
                ..ffffffff...c..........
                ..fff..ff...............
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `)
        }
        if (Directions == 6) {
            Hero.setImage(img`
                ........................
                ........................
                .......ff...............
                .....ff22ff.............
                ...fff2222fff...........
                ..fff222222fff..........
                ..fff222222fff..........
                ..feeeeeeeeeeff.........
                .ffe22222222eff.........
                .fffffeeeefffff.........
                fdfefbf44fbfeff.........
                fbfe41fddf14ef..........
                fbffe4dddd4efe..........
                fcfef22222f4e...........
                .ff4f44554f4e...........
                ....ffffffdde...........
                .....ffffedde...........
                ..........ee............
                .........ccc............
                ........cc1cc...........
                .........c1c............
                .........c1c............
                .........c1c............
                .........c1c............
                `)
        }
        if (Directions == 9) {
            Hero.setImage(img`
                ...............ff.......
                .............ff2ffff....
                ............ff2feeeeff..
                ...........ff22feeeeeff.
                ...........feeeeffeeeef.
                ..........fe2222eefffff.
                ..........f2effff222efff
                ..........fffeeeffffffff
                ..........fee44fbe44efef
                ...........feddfb4d4eef.
                ..........c.eeddd4eeef..
                ....ccccccceddee2222f...
                .....dddddcedd44e444f...
                ......ccccc.eeeefffff...
                ..........c...ffffffff..
                ...............ff..fff..
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `)
        }
    }
})
